export const roleSchemas = {
  telecaller: [
    { name: 'date', label: 'Date', type: 'date', required: true },
    { name: 'callsMade', label: 'Total Calls Made', type: 'number', required: true },
    { name: 'leadsGenerated', label: 'Leads Generated', type: 'number', required: true },
    { name: 'followUps', label: 'Follow-ups Done', type: 'number', required: true },
    { name: 'conversions', label: 'Conversions/Sales Closed', type: 'number', required: true },
    { name: 'remarks', label: 'Remarks/Notes', type: 'textarea', required: false },
    { name: 'recordingLink', label: 'Call Recording Link', type: 'url', required: false },
    { name: 'screenshotUrl', label: 'Attach Screenshot (Optional)', type: 'image', required: false },
  ],
  developer: [
    { name: 'date', label: 'Date', type: 'date', required: true },
    { name: 'projectName', label: 'Project/Module Name', type: 'text', required: true },
    { name: 'taskAssigned', label: 'Task Assigned', type: 'select', options: ['Frontend', 'Backend', 'Bugfix', 'Other'], required: true },
    { name: 'taskStatus', label: 'Task Status', type: 'select', options: ['Pending', 'In Progress', 'Completed', 'Blocked'], required: true },
    { name: 'hoursWorked', label: 'Hours Worked', type: 'number', required: true },
    { name: 'bugsFixed', label: 'Bugs Fixed Count', type: 'number', required: false },
    { name: 'description', label: 'Proper Description', type: 'textarea', required: true },
    { name: 'screenshotUrl', label: 'Attach Screenshot (Optional)', type: 'image', required: false },
  ],
  video_editor: [
    { name: 'date', label: 'Date', type: 'date', required: true },
    { name: 'projectName', label: 'Project/Video Name', type: 'text', required: true },
    { name: 'videoType', label: 'Video Upload Type', type: 'select', options: ['Reel', 'Long Video'], required: true },
    { name: 'channel', label: 'Upload Channel', type: 'select', options: ['kisanChoice', 'tejomarg', 'kisandigital', 'Other'], required: true },
    { name: 'editingStatus', label: 'Editing Status', type: 'select', options: ['Draft', 'Review', 'Final'], required: true },
    { name: 'duration', label: 'Duration of Video (mins)', type: 'number', required: true },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false },
    { name: 'videoFile', label: 'Upload Final Video', type: 'video', required: true },
  ],
  social_media: [
    { name: 'date', label: 'Date', type: 'date', required: true },
    { name: 'youtube', label: 'YouTube', type: 'platform-metric', options: ['KisanChoice', 'Tejomarg', 'Tm24news', 'shri shri SSPF', 'KisanDigital'] },
    { name: 'facebook', label: 'Facebook', type: 'platform-metric', options: ['KisanChoice', 'Tejomarg', 'Tm24news', 'shri shri SSPF', 'KisanDigital'] },
    { name: 'instagram', label: 'Instagram', type: 'platform-metric', options: ['KisanChoice', 'Tejomarg', 'Tm24news', 'shri shri SSPF', 'KisanDigital'] },
    { name: 'linkedin', label: 'LinkedIn', type: 'platform-metric', options: ['Anand Sir', 'KisanChoice'] },
    { name: 'pinterest', label: 'Pinterest', type: 'platform-metric', options: ['KisanChoice', 'Tejomarg', 'Tm24news', 'shri shri SSPF', 'KisanDigital'] },
    { name: 'contentType', label: 'Content Type', type: 'select', options: ['Reel', 'Post', 'Story', 'Video', 'Shorts'], required: true },
    { name: 'engagement', label: 'Engagement Metrics (optional)', type: 'text', required: false },
    { name: 'postLink', label: 'Post Link', type: 'url', required: true },
    { name: 'remarks', label: 'Remarks', type: 'textarea', required: false },
    { name: 'videoFile', label: 'Upload Video (Optional)', type: 'video', required: false },
  ]
};
